import UserIcon from "../../../assets/images/user2.png";

export const data = [
  {
    src: UserIcon,
    name: "Esther Howard",
    desc: "Of course I can...",
    isOnline: true,
    lastSeen: "",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Marvin McKinney",
    desc: "That’s great!!",
    isOnline: false,
    lastSeen: "1 min",
    msgUnread: 2,
  },
  {
    src: UserIcon,
    name: "Kathryn Murphy",
    desc: "Counting yor slot...",
    isOnline: false,
    lastSeen: "10 min",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Floyd Miles",
    desc: "Let me know...",
    isOnline: false,
    lastSeen: "6 hour",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Albert Flores",
    desc: "All faith needs feet...",
    isOnline: false,
    lastSeen: "20 min",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Brooklyn Simmons",
    desc: "Glad to hear from you...",
    isOnline: false,
    lastSeen: "7 day",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Kristin Watson",
    desc: "Esther Howard.",
    isOnline: false,
    lastSeen: "5 sec",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Annette Black",
    desc: "Esther Howard.",
    isOnline: false,
    lastSeen: "2 week",
    msgUnread: 0,
  },
  {
    src: UserIcon,
    name: "Savannah Nguyen",
    desc: "Esther Howard.",
    isOnline: false,
    lastSeen: "1 month",
    msgUnread: 0,
  },
];
